branches:
  - name: "main"
    protection:
      required_status_checks:
        strict: true
        contexts: ["ci"]
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      enforce_admins: false
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false

  - name: "dev"
    protection:
      required_status_checks:
        contexts: ["ci"]
      required_pull_request_reviews:
        required_approving_review_count: 1
      enforce_admins: false